<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <RootNamespace>RaylibCoop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="6.*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="tests/**" />
    <Compile Remove="examples/**" />
  </ItemGroup>
</Project>
